name: NFL Transactions Tracker

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:  # allows you to trigger it manually from GitHub

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          NFL_WEBHOOK: ${{ secrets.NFL_WEBHOOK }}
          SEAHAWKS_WEBHOOK: ${{ secrets.SEAHAWKS_WEBHOOK }}
        run: python nfl_transactions_tracker.py